In [ ]:
#Name: Tirthankar Datta
#Registration Number: 24-52-28
#Programme: PhD
#Assignment Number: 2

In [11]:
#Question 1

import numpy as np
var1=np.arange(0,31,1)
print(var1)
print("Shape :"+str(var1.shape))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Shape :(31,)


In [13]:
var2=var1[:-1].reshape(3,10)
print(var2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [15]:
var3=var1[:-1].reshape(3,5,2)
print(var3)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]


In [17]:
var2[1,0]=-1
print(var2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [-1 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [19]:
print(var1)
print(var3)

[ 0  1  2  3  4  5  6  7  8  9 -1 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[-1 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]


In [21]:
sum_over_second_dim=np.sum(var3,axis=1)
print(sum_over_second_dim)

[[ 20  25]
 [ 59  75]
 [120 125]]


In [23]:
sum_over_third_dim=np.sum(var3,axis=2)
print(sum_over_third_dim)

[[ 1  5  9 13 17]
 [10 25 29 33 37]
 [41 45 49 53 57]]


In [25]:
sum_over_first_second=np.sum(var3,axis=(0,2))
print(sum_over_first_second)

[ 52  75  87  99 111]


In [27]:
print(var2[1:2])
print(var2[0:,-1])
print(var2[:2,-2:])

[[-1 11 12 13 14 15 16 17 18 19]]
[ 9 19 29]
[[ 8  9]
 [18 19]]


In [29]:
#Question 2

arr=np.arange(0,10,1)
arr_b=arr+1
print(arr_b)

[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
arr2=arr+arr.reshape(10,1)
print(arr2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]


In [35]:
dataset=np.exp(np.random.randn(50,5))
print(dataset)

[[ 0.61105159  0.44300341  0.14898338  0.74302806  2.35541348]
 [ 0.70786584  9.06742371  1.42792013  0.47160835  0.31655374]
 [13.68768163  5.35762069  0.59214471  0.96822704  0.61917382]
 [ 1.56160384  0.63870212  3.06962323  0.79152161  1.55013182]
 [ 0.18242826  1.46992857  1.90473368  0.3963871   0.21271932]
 [ 0.42127946  0.32028772  3.44584785  0.68381577  0.6272904 ]
 [ 2.05803813  1.82559543 39.77221344  0.92237894  0.44234843]
 [ 2.29392588  3.32619634  0.80462363  0.51031767  1.91751238]
 [ 0.89567089  0.79977575  0.54207956  1.92060387  0.83351968]
 [ 0.17537369  1.87626186  0.92829949  0.94838375  4.19627839]
 [ 0.28552175  0.17959479  4.84267789  0.21810311  0.3965047 ]
 [ 1.54061806  1.0569967   1.53679039  0.70233797  0.98493012]
 [ 1.93759264  0.14594872  0.80564668  0.32654564  1.6253854 ]
 [ 0.51527872  5.47221271  1.78095473  1.07919637  1.20077478]
 [ 4.11159419  0.31389986  0.66852752  0.96269262  0.13609841]
 [ 0.27287904  4.51410153  1.80000257  0.20862791  1.29

In [39]:
mean=np.mean(dataset,axis=0)
sd=np.std(dataset,axis=0)

In [41]:
print(mean)
print(sd)

[1.50035376 1.67675571 2.4740047  1.45547692 1.50578509]
[2.06369877 1.7842416  5.53262232 2.08527582 1.28175562]


In [45]:
standardise=(dataset-mean)/sd
new_mean=np.mean(standardise,axis=0)
normalized=np.std(standardise,axis=0)
print(new_mean)
print(normalized)

[ 6.88338275e-17  2.63261635e-16 -1.11022302e-17 -9.15933995e-18
 -7.10542736e-17]
[1. 1. 1. 1. 1.]


In [49]:
#Question 3

def vandermonde(N):
    vec=np.arange(N)+1
    vander=vec.reshape(N,1)
    vander=vander**np.arange(N)
    return vander
vander=vandermonde(12)
print(vander)

[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
       117649      823543     57

In [51]:
x=np.ones(12)
b=np.dot(vander,x)
print(b)

[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 1.22713351e+09
 9.43953692e+08 3.73692871e+09 3.10225064e+08 3.10073456e+09]


In [53]:
inverse=np.linalg.inv(vander)
res=np.dot(inverse,b)
print(res)

[0.99620819 1.00462723 0.99909973 1.00006104 0.99999666 1.00000048
 0.99999995 1.         1.         1.         1.         1.        ]


In [55]:
#The expected result was that all the elements of the matrix would be exactly 1. However, not all results come out to be 1.

In [57]:
res_new=np.linalg.solve(vander,b)
print(res_new)

[0.99998827 1.00002951 0.99997139 1.00001427 0.99999595 1.00000068
 0.99999993 1.         1.         1.         1.         1.        ]


In [59]:
#The result is closer to the expected value.